djangoapp/urls.py
from django.urls import path, include


urlpatterns = [
    path('myapp/', include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from . import views


app_name = 'myapp'


urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('new', views.book_create, name='book_new'),
    path('edit/<int:pk>', views.book_update, name='book_edit'),
    path('delete/<int:pk>', views.book_delete, name='book_delete'),
]

myapp/models.py
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse


# Create your models here.
class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('book_edit', kwargs={'pk': self.pk})

myapp/views.py
# import loading from django template
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
# import class
from myapp.models import Book


# Create your views here.
class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages']


def home(request):
    return render(request, "books/home.html")


def book_list(request, template_name='books/book_list.html'):
    book = Book.objects.all()
    data = {}
    data['object_list'] = book
    return render(request, template_name, data)


def book_view(request, pk, template_name='books/book_detail.html'):
    book = get_object_or_404(Book, pk=pk)
    return render(request, template_name, {'object': book})


def book_create(request, template_name='books/book_form.html'):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('book_list')
    return render(request, template_name, {'form': form})


def book_update(request, pk, template_name='books/book_form.html'):
    book = get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('book_list')
    return render(request, template_name, {'form': form})


def book_delete(request, pk, template_name='books/book_confirm_delete.html'):
    book= get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        book.delete()
        return redirect('book_list')
    return render(request, template_name, {'object': book})

myapp/templates/books/base.html
{% load static %}

<html>
<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="header">
        <h1><a href="/">Django CRUD Example</a></h1>
    </div><!-- header -->
    <div id="content">
        {% block content %}
        {% endblock %}
    </div><!-- content -->
</body>
</html>

myapp/templates/books/book_confirm_delete.html
<h1>Book Delete</h1>
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

myapp/templates/books/book_details.html
{% extends "books/base.html" %}

{% block content %}
<h1>Book Details</h1>
<h2>Name: {{object.name}}</h2>
Pages: {{ object.pages }}
{% endblock %}

myapp/templates/books/book_form.html
{% extends "books:base.html" %}

{% block content %}
<h1>Book Edit</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

myapp/templates/books/book_list.html
{% extends "books/base.html" %}

{% block content %}
<h1>Books</h1>

<table border="1">
    <thead>
    <tr>
        <th>Name</th>
        <th>Pages</th>
        <th>View</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    <h2><a href="{% url 'myapp:book_list' %}">Books FBV User</a></h2>
    {% for book in object_list %}
        <tr>
            <td>{{ book.name }}</td>
            <td>{{ book.pages }}</td>
            <td><a href="{% url "myapp:book_edit" book.id %}">edit</a></td>
            <td><a href="{% url "myapp:book_delete" book.id %}">delete</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<a href="{% url "myapp:book_new" %}">New</a>
{% endblock %}

myapp/templates/books/home.html
{% extends "books/base.html" %}

{% block content %}

<a href="{% url 'books_cbv:book_list' %}">Class Based Views</a><br>
<a href="{% url 'books_fbv:book_list' %}">Function Based Views</a><br>    
<a href="{% url 'books_fbv_user:book_list' %}">Function Based Views with User Access</a><br>    

{% endblock %}